### ISSUE TITLE
test_webpush failing

### ISSUE THREAD

**Issue by rpappalax** [mozilla-services/simplepush_test#6]
simplepush_test.pushtest.test_webpush.test_basic_delivery ... FAIL
simplepush_test.pushtest.test_webpush.test_delivery_repeat_without_ack ... FAIL
simplepush_test.pushtest.test_webpush.test_multiple_delivery_repeat_without_ack ... FAIL
simplepush_test.pushtest.test_webpush.test_multiple_delivery_with_single_ack ... FAIL
simplepush_test.pushtest.test_webpush.test_multiple_delivery_with_multiple_ack ... FAIL
simplepush_test.pushtest.test_webpush.test_no_delivery_to_unregistered ... FAIL
simplepush_test.pushtest.test_webpush.test_ttl_0_connected ... FAIL
simplepush_test.pushtest.test_webpush.test_ttl_0_not_connected ... ok
simplepush_test.pushtest.test_webpush.test_ttl_expired ... ok

**Comment by jonathanpmartins** [comment]
to me is failing too. I'm using Ubuntu 14.04.3 - Python 2.7.11, and the latest version of mozilla autpush https://github.com/mozilla-services/autopush

**Comment by jrconlin** [comment]
@jonathanpmartins: Autopush has since incorporated it's own integration test into itself. This package has fallen out of maintenance since then, although I do tend to use the smoke_test.py on occasion to test some installations. 

I'll amend the package to include a note about that next week.

**Comment by jonathanpmartins** [comment]
Thanks for the explanation! The original docs point to this repository: http://autopush.readthedocs.org/en/latest/running.html

**Comment by jonathanpmartins** [comment]
The obsolete tester reference was removed. I think this issue can be closed. @jrconlin @rpappalax

**Comment by jrconlin** [comment]
This package has been noted as obsolete. 

https://github.com/mozilla-services/autopush/commit/547311de2c071b0a7e3f00c845ee9622646ae349
